### FILMS

### All films
GET http://localhost:3000/films 

### One Film
GET http://localhost:3000/films/***

### New Film
POST http://localhost:3000/films
content-type: application/json

{
    "title": ,
    "releaseYear": 193,
    "rating": "PG-13",
    "actors": [{"actorId": 5001, "name": "Sam Neill"}],
    "category": "Action",
    "director": "Steven Spielberg",
    "length": "2 hr 7 min"
}

### Update Film- Adding a spoiler, adding an actor 
PUT http://localhost:3000/films/***
content-type: application/json

{
    "title": "Jurassic Park **SPOILER- everyone dies**",
    "releaseYear": 1993,
    "rating": "PG-13",
    "actors": [{"actorId": 5001, "name": "Sam Neill", "actorId": 5002, "name": "Laura Dern"}],
    "category": "Action",
    "director": "Steven Spielberg",
    "length": "2 hr 7 min"
}

### Delete Film
DELETE http://localhost:3000/films/***


### ACTORS
### All Actors
GET http://localhost:3000/actors

### One Actor
GET http://localhost:3000/actors/***

### New Actor
POST http://localhost:3000/actors
content-type: application/json

{
    "actorId": 6001,
    "name": "Dwayne Johnson"
}

### Update Actor- adding an alias
PUT http://localhost:3000/actors/***
content-type: application/json

{
    "actorId": 6001,
    "name": "Dwayne 'The Rock' Johnson"
}

### Delete Actor
DELETE http://localhost:3000/actors/***