### FILMS
### Get all films
GET https://emasonproject2.onrender.com/films

### Get one film
GET https://emasonproject2.onrender.com/oneFilm/***

### Add new film
POST https://emasonproject2.onrender.com/newFilm 
content-type: application/json

{
    "title": "Jurassic Park",
    "releaseYear": 1993,
    "rating": "PG-13",
    "actors": [{"actorId": 5001, "name": "Sam Neill"}],
    "category": "Action",
    "director": "Steven Spielberg",
    "length": "2 hr 7 min"
}


### Update Film - add spoiler, add actor
PUT https://emasonproject2.onrender.com/updateFilm*** 
content-type: application/json

{
    "title": "Jurassic Park **SPOILER- everyone dies**",
    "releaseYear": 1993,
    "rating": "PG-13",
    "actors": [{"actorId": 5001, "name": "Sam Neill", "actorId": 5002, "name": "Laura Dern"}],
    "category": "Action",
    "director": "Steven Spielberg",
    "length": "2 hr 7 min"
}

### Delete film
DELETE https://emasonproject2.onrender.com/deleteFilm/***

### ACTORS
### Get all actors
GET https://emasonproject2.onrender.com/actors

### Get one actor
GET https://emasonproject2.onrender.com/oneActor/***

### Add new actor
POST https://emasonproject2.onrender.com/newActor 
content-type: application/json

{
    "actorId": 6001,
    "name": "Dwayne Johnson"
}

### Update actor - add alias
PUT https://emasonproject2.onrender.com/updateActor/***
content-type: application/json

{
    "actorId": 6001,
    "name": "Dwayne 'The Rock' Johnson"
}

### Delete Actor
DELETE https://emasonproject2.onrender.com/deleteActor/***
